### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ldidry** [PhieF/OhMyGif#1]
Hello,

Could you add (or document if it exists already) an API?

I would happily develop a service to be able to integrate your service with Mattermost slash commands like I [did for giphy](https://framagit.org/framasoft/giphymathooker).

Suggested endpoints:
- /search => be able to search, returns an array of gif URLs
- /random => return a random gif URL

**Comment by PhieF** [comment]
oh nice I didn't see this report !

well you can search for some gif just by calling 
https://omg.phie.ovh/get.php?query=criquette

**Comment by ldidry** [comment]
Merci ! Voilà qui est fait : https://framagit.org/framasoft/giphymathooker/commit/4535fcfd74eb718d65a8785e6ff75f37925f5064

**Comment by bc1bb** [comment]
Excellent :D 
Framasoft compte ouvrir son instance ?

**Comment by ldidry** [comment]
Non, pour l'instant on va plutôt taper sur celle de @PhieF, si ça le dérange pas (c'est même en dur dans le code pour l'instant (flemme))

**Comment by PhieF** [comment]
Oui y'a pas de souci ! Merci pour l'intégration !
